# Generated by Django 2.1.7 on 2019-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
