# Generated by Django 2.1.7 on 2019-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=25)),
                ('price', models.FloatField()),
                ('sponsored', models.BooleanField(default=False)),
                ('hours', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=2083)),
                ('rating', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
