# Generated by Django 2.1.7 on 2019-04-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='event',
            field=models.CharField(default='tbd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.CharField(default='tbd', max_length=200),
            preserve_default=False,
        ),
    ]
